#!/bin/sh

if [ "$1" = "" ]; then
  echo "Error: must pass file name as argument"
  exit
fi

FILE_NAME="$1"
SPEC_NAME="$FILE_NAME.spec"
SCRIPT_NAME="scripts/$FILE_NAME/main.py"
CONFIG_NAME="scripts/$FILE_NAME/config.ini" # TODO: auto-generate this file
BUILD_NAME="build"

THIS_DIR="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"
OUTPUT_PATH="$THIS_DIR/$FILE_NAME"
SPEC_PATH="$THIS_DIR/$SPEC_NAME"
SCRIPT_PATH="$THIS_DIR/$SCRIPT_NAME"
BUILD_PATH="$THIS_DIR/$BUILD_NAME"

# build
pyinstaller "$SCRIPT_PATH" --clean --onefile --name "$OUTPUT_PATH" --distpath "$THIS_DIR" -y --add-data "$CONFIG_NAME:."
# cleanup
deactivate
rm -rf "$BUILD_PATH"
rm "$SPEC_PATH"
