name: Build EXE

on:
  workflow_dispatch:
    inputs:
      string:
        type: string
        description: Test Name
jobs:
  build_exe:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-10.15 ]
    name: Build Launcher for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check out the Git repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package"
        run: python -m pip install -e .

      - name: "Read name from user input"
        id: get_test_name
        run: echo "::set-output name=name::${{ github.event.inputs.string }}"

      - name: "Generate exe name"
        id: get_exe_name
        run: python -c "import github_action_test.utils.build as b; print('::set-output name=name::' + b.generate_exe_name_for_script('${{ steps.get_test_name.outputs.name }}'))"

      - name: "Build executable"
        run: python -m github_action_test.utils.build --name ${{ github.event.inputs.string }}

      - name: "Tar artifacts to maintain permissions on POSIX"
        if: ${{ runner.os == 'linux' || runner.os == 'macos' }}
        run: tar -C dist -cvzf ${{ steps.get_exe_name.outputs.name }}.tar.gz .

      - name: "Add OS name to artifact"
        id: get_artifact_name
        run: echo "::set-output name=name::${{ steps.get_exe_name.outputs.name }}-${{ runner.os }}"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_artifact_name.outputs.name }}
          path: |
            *.tar.gz
            dist/*.exe

