name: Build Release

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Production Test Name
        options:
        - script_a
jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: "Check out the Git repository"
        uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package"
        run: python -m pip install -e .

      - name: "Read name from user input"
        id: get_test_name
        run: echo "::set-output name=name::${{ github.event.inputs.choice }}"

      - name: "Generate tag name"
        id: get_tag_name
        run: python -c "import github_action_test.utils.build as b; print('::set-output name=name::' + b.generate_tag_name_for_script('${{ steps.get_test_name.outputs.name }}'))"

      - name: "Tag latest commit"
        run: git tag ${{ steps.get_tag_name.outputs.name }} && git push --tags

      - name: "Build executable"
        run: python -m github_action_test.utils.build --name ${{ github.event.inputs.choice }}

      - name: "Tar artifacts to maintain permissions on POSIX"
        if: ${{ runner.os == 'linux' || runner.os == 'macos' }}
        run: tar -C dist -cvzf ${{ steps.get_tag_name.outputs.name }}.tar.gz .

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_tag_name.outputs.name }}
          path: |
            *.tar.gz
            dist/*.exe

