name: Test Inputs

on:
  workflow_dispatch:
    inputs:
      string:
        type: string
        description: Version number
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "string is ${{ github.event.inputs.string }}"
          echo "choice is ${{ github.event.inputs.choice }}"
